In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#2.veri onisleme
#2.1.veri yukleme
veriler = pd.read_csv('veriler.csv')
#pd.read_csv("veriler.csv")
#test
print(veriler)
Yas = veriler.iloc[:,1:4].values
print(Yas)

#encoder: Kategorik -> Numeric
ulke = veriler.iloc[:,0:1].values
print(ulke)

from sklearn import preprocessing

le = preprocessing.LabelEncoder()

ulke[:,0] = le.fit_transform(veriler.iloc[:,0])

print(ulke)

ohe = preprocessing.OneHotEncoder()
ulke = ohe.fit_transform(ulke).toarray()
print(ulke)

#encoder: Kategorik -> Numeric
c = veriler.iloc[:,-1:].values
print(c)


from sklearn import preprocessing

le = preprocessing.LabelEncoder()

c[:,-1] = le.fit_transform(veriler.iloc[:,-1])

print(c)


#numpy dizileri dataframe donusumu
sonuc = pd.DataFrame(data=ulke, index = range(22), columns = ['fr','tr','us'])
print(sonuc)

sonuc2 = pd.DataFrame(data=Yas, index = range(22), columns = ['boy','kilo','yas'])
print(sonuc2)

cinsiyet = veriler.iloc[:,-1].values
print(cinsiyet)

sonuc3 = pd.DataFrame(data = c[:,:1], index = range(22), columns = ['cinsiyet'])
print(sonuc3)


#dataframe birlestirme islemi
s=pd.concat([sonuc,sonuc2], axis=1)
print(s)

s2=pd.concat([s,sonuc3], axis=1)
print(s2)

#verilerin egitim ve test icin bolunmesi
from sklearn.model_selection import train_test_split

x_train, x_test,y_train,y_test = train_test_split(s,sonuc3,test_size=0.33, random_state=0)


from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

y_pred = regressor.predict(x_test)

boy = s2.iloc[:,3:4].values
print(boy)
sol = s2.iloc[:,:3]
sag = s2.iloc[:,4:]

veri = pd.concat([sol,sag],axis=1)

x_train, x_test,y_train,y_test = train_test_split(veri,boy,test_size=0.33, random_state=0)


r2 = LinearRegression()
r2.fit(x_train,y_train)

y_pred = r2.predict(x_test)

   ulke  boy  kilo  yas cinsiyet
0    tr  130    30   10        e
1    tr  125    36   11        e
2    tr  135    34   10        k
3    tr  133    30    9        k
4    tr  129    38   12        e
5    tr  180    90   30        e
6    tr  190    80   25        e
7    tr  175    90   35        e
8    tr  177    60   22        k
9    us  185   105   33        e
10   us  165    55   27        k
11   us  155    50   44        k
12   us  160    58   39        k
13   us  162    59   41        k
14   us  167    62   55        k
15   fr  174    70   47        e
16   fr  193    90   23        e
17   fr  187    80   27        e
18   fr  183    88   28        e
19   fr  159    40   29        k
20   fr  164    66   32        k
21   fr  166    56   42        k
[[130  30  10]
 [125  36  11]
 [135  34  10]
 [133  30   9]
 [129  38  12]
 [180  90  30]
 [190  80  25]
 [175  90  35]
 [177  60  22]
 [185 105  33]
 [165  55  27]
 [155  50  44]
 [160  58  39]
 [162  59  41]
 [167  62  55]
 [174  70  47]
 

In [4]:
import statsmodels.api as sm

In [5]:
X = np.append(arr = np.ones((22,1)).astype(int), values=veri,axis=1)
X

array([[1, 0.0, 1.0, 0.0, 30, 10, 0],
       [1, 0.0, 1.0, 0.0, 36, 11, 0],
       [1, 0.0, 1.0, 0.0, 34, 10, 1],
       [1, 0.0, 1.0, 0.0, 30, 9, 1],
       [1, 0.0, 1.0, 0.0, 38, 12, 0],
       [1, 0.0, 1.0, 0.0, 90, 30, 0],
       [1, 0.0, 1.0, 0.0, 80, 25, 0],
       [1, 0.0, 1.0, 0.0, 90, 35, 0],
       [1, 0.0, 1.0, 0.0, 60, 22, 1],
       [1, 0.0, 0.0, 1.0, 105, 33, 0],
       [1, 0.0, 0.0, 1.0, 55, 27, 1],
       [1, 0.0, 0.0, 1.0, 50, 44, 1],
       [1, 0.0, 0.0, 1.0, 58, 39, 1],
       [1, 0.0, 0.0, 1.0, 59, 41, 1],
       [1, 0.0, 0.0, 1.0, 62, 55, 1],
       [1, 1.0, 0.0, 0.0, 70, 47, 0],
       [1, 1.0, 0.0, 0.0, 90, 23, 0],
       [1, 1.0, 0.0, 0.0, 80, 27, 0],
       [1, 1.0, 0.0, 0.0, 88, 28, 0],
       [1, 1.0, 0.0, 0.0, 40, 29, 1],
       [1, 1.0, 0.0, 0.0, 66, 32, 1],
       [1, 1.0, 0.0, 0.0, 56, 42, 1]], dtype=object)

In [6]:
X_l = veri.iloc[:,[0,1,2,3,4,5]].values
x_l = np.array(X_l, dtype=float)

In [9]:
model = sm.OLS(boy,X_l).fit()

TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''