<h1 style="text-align:center">Ödev 2</h1>

* Veri kümesini indirin.
* Gerekli/gereksiz bağımsız değişkenleri bulun.
* 5 farklı yöntemle regresyon modellerini çıkarın.
  * [MLR](#Multi-Linear-Regression)
  * [PR](#Polynomial-Regression)
  * [SVM](#Support-Vector-Machine-Regression)
  * [DT](#Desicion-Tree)
  * [RF](#Random-Forest)
* Yöntemleri karşılaştırın.
* 10 yıl tecrübeli ve 100 puan almış bir CEO ile aynı özelliklere sahip bir müdürün maaşlarını tahmin edip sonuçları yorumlayın.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

initial_data = pd.read_csv("maaslar_yeni.csv")

In [2]:
initial_data.head()

Calisan ID             unvan  UnvanSeviyesi  Kidem  Puan  maas
0           1             Cayci              1      5    70  2250
1           2          Sekreter              2      5    70  2500
2           3  Uzman Yardimcisi              3      5    70  3000
3           4             Uzman              4      5    70  4000
4           5  Proje Yoneticisi              5      5    70  5500

In [3]:
initial_data.describe()

Calisan ID  UnvanSeviyesi      Kidem       Puan          maas
count   30.000000      30.000000  30.000000  30.000000     30.000000
mean    15.500000       5.500000   5.433333  59.066667  10861.666667
std      8.803408       2.921384   2.686920  25.330823  13468.313281
min      1.000000       1.000000   1.000000   2.000000   2000.000000
25%      8.250000       3.000000   4.000000  44.000000   3000.000000
50%     15.500000       5.500000   5.000000  70.000000   5450.000000
75%     22.750000       8.000000   7.750000  70.000000  12000.000000
max     30.000000      10.000000  10.000000  99.000000  60000.000000

In [4]:
x_df = initial_data.iloc[:,2:5]
y_df = initial_data.iloc[:,-1:]

In [5]:
x_df

UnvanSeviyesi  Kidem  Puan
0               1      5    70
1               2      5    70
2               3      5    70
3               4      5    70
4               5      5    70
5               6      5    70
6               7      5    70
7               8      5    70
8               9      5    70
9              10      5    70
10              1      7    99
11              2      7     9
12              3      7    62
13              4      4    38
14              5      1    80
15              6      2    35
16              7      8    99
17              8      4    58
18              9      2    20
19             10      4    42
20              1      8    11
21              2      2    53
22              3      8    50
23              4      9    91
24              5      9    71
25              6      1     2
26              7     10    81
27              8     10    38
28              9      1    50
29             10      9    83

In [6]:
from sklearn import preprocessing
ohe = preprocessing.OneHotEncoder()

In [7]:
unvan_column = x_df.iloc[:,0:1].values
unvan_column

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]], dtype=int64)

In [8]:
unvan_column = ohe.fit_transform(unvan_column).toarray()

In [9]:
unvan_column

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 

In [10]:
unvan_df = pd.DataFrame(data=unvan_column, index=range(len(unvan_column)), columns=["Cayci","Sekreter","Uzman Yardimcisi","Uzman","Proje Yoneticisi","Sef","Mudur","Direktor","C-level","CEO"])
unvan_df

Cayci  Sekreter  Uzman Yardimcisi  Uzman  Proje Yoneticisi  Sef  Mudur  \
0     1.0       0.0               0.0    0.0               0.0  0.0    0.0   
1     0.0       1.0               0.0    0.0               0.0  0.0    0.0   
2     0.0       0.0               1.0    0.0               0.0  0.0    0.0   
3     0.0       0.0               0.0    1.0               0.0  0.0    0.0   
4     0.0       0.0               0.0    0.0               1.0  0.0    0.0   
5     0.0       0.0               0.0    0.0               0.0  1.0    0.0   
6     0.0       0.0               0.0    0.0               0.0  0.0    1.0   
7     0.0       0.0               0.0    0.0               0.0  0.0    0.0   
8     0.0       0.0               0.0    0.0               0.0  0.0    0.0   
9     0.0       0.0               0.0    0.0               0.0  0.0    0.0   
10    1.0       0.0               0.0    0.0               0.0  0.0    0.0   
11    0.0       1.0               0.0    0.0               0.0  0.0    0.0   
12    0.0       0.0               1.0    0.0               0.0  0.0    0.0   
13    0.0       0.0               0.0    1.0               0.0  0.0    0.0   
14    0.0       0.0               0.0    0.0               1.0  0.0    0.0   
15    0.0       0.0               0.0    0.0               0.0  1.0    0.0   
16    0.0       0.0               0.0    0.0               0.0  0.0    1.0   
17    0.0       0.0               0.0    0.0               0.0  0.0    0.0   
18    0.0       0.0               0.0    0.0               0.0  0.0    0.0   
19    0.0       0.0               0.0    0.0               0.0  0.0    0.0   
20    1.0       0.0               0.0    0.0               0.0  0.0    0.0   
21    0.0       1.0               0.0    0.0               0.0  0.0    0.0   
22    0.0       0.0               1.0    0.0               0.0  0.0    0.0   
23    0.0       0.0               0.0    1.0               0.0  0.0    0.0   
24    0.0       0.0               0.0    0.0               1.0  0.0    0.0   
25    0.0       0.0               0.0    0.0               0.0  1.0    0.0   
26    0.0       0.0               0.0    0.0               0.0  0.0    1.0   
27    0.0       0.0               0.0    0.0               0.0  0.0    0.0   
28    0.0       0.0               0.0    0.0               0.0  0.0    0.0   
29    0.0       0.0               0.0    0.0               0.0  0.0    0.0   

    Direktor  C-level  CEO  
0        0.0      0.0  0.0  
1        0.0      0.0  0.0  
2        0.0      0.0  0.0  
3        0.0      0.0  0.0  
4        0.0      0.0  0.0  
5        0.0      0.0  0.0  
6        0.0      0.0  0.0  
7        1.0      0.0  0.0  
8        0.0      1.0  0.0  
9        0.0      0.0  1.0  
10       0.0      0.0  0.0  
11       0.0      0.0  0.0  
12       0.0      0.0  0.0  
13       0.0      0.0  0.0  
14       0.0      0.0  0.0  
15       0.0      0.0  0.0  
16       0.0      0.0  0.0  
17       1.0      0.0  0.0  
18       0.0      1.0  0.0  
19       0.0      0.0  1.0  
20       0.0      0.0  0.0  
21       0.0      0.0  0.0  
22       0.0      0.0  0.0  
23       0.0      0.0  0.0  
24       0.0      0.0  0.0  
25       0.0      0.0  0.0  
26       0.0      0.0  0.0  
27       1.0      0.0  0.0  
28       0.0      1.0  0.0  
29       0.0      0.0  1.0

In [11]:
x_df.drop(columns=["UnvanSeviyesi"], inplace=True)
x_df = pd.concat([x_df,unvan_df], axis=1)
x_df

Kidem  Puan  Cayci  Sekreter  Uzman Yardimcisi  Uzman  Proje Yoneticisi  \
0       5    70    1.0       0.0               0.0    0.0               0.0   
1       5    70    0.0       1.0               0.0    0.0               0.0   
2       5    70    0.0       0.0               1.0    0.0               0.0   
3       5    70    0.0       0.0               0.0    1.0               0.0   
4       5    70    0.0       0.0               0.0    0.0               1.0   
5       5    70    0.0       0.0               0.0    0.0               0.0   
6       5    70    0.0       0.0               0.0    0.0               0.0   
7       5    70    0.0       0.0               0.0    0.0               0.0   
8       5    70    0.0       0.0               0.0    0.0               0.0   
9       5    70    0.0       0.0               0.0    0.0               0.0   
10      7    99    1.0       0.0               0.0    0.0               0.0   
11      7     9    0.0       1.0               0.0    0.0               0.0   
12      7    62    0.0       0.0               1.0    0.0               0.0   
13      4    38    0.0       0.0               0.0    1.0               0.0   
14      1    80    0.0       0.0               0.0    0.0               1.0   
15      2    35    0.0       0.0               0.0    0.0               0.0   
16      8    99    0.0       0.0               0.0    0.0               0.0   
17      4    58    0.0       0.0               0.0    0.0               0.0   
18      2    20    0.0       0.0               0.0    0.0               0.0   
19      4    42    0.0       0.0               0.0    0.0               0.0   
20      8    11    1.0       0.0               0.0    0.0               0.0   
21      2    53    0.0       1.0               0.0    0.0               0.0   
22      8    50    0.0       0.0               1.0    0.0               0.0   
23      9    91    0.0       0.0               0.0    1.0               0.0   
24      9    71    0.0       0.0               0.0    0.0               1.0   
25      1     2    0.0       0.0               0.0    0.0               0.0   
26     10    81    0.0       0.0               0.0    0.0               0.0   
27     10    38    0.0       0.0               0.0    0.0               0.0   
28      1    50    0.0       0.0               0.0    0.0               0.0   
29      9    83    0.0       0.0               0.0    0.0               0.0   

    Sef  Mudur  Direktor  C-level  CEO  
0   0.0    0.0       0.0      0.0  0.0  
1   0.0    0.0       0.0      0.0  0.0  
2   0.0    0.0       0.0      0.0  0.0  
3   0.0    0.0       0.0      0.0  0.0  
4   0.0    0.0       0.0      0.0  0.0  
5   1.0    0.0       0.0      0.0  0.0  
6   0.0    1.0       0.0      0.0  0.0  
7   0.0    0.0       1.0      0.0  0.0  
8   0.0    0.0       0.0      1.0  0.0  
9   0.0    0.0       0.0      0.0  1.0  
10  0.0    0.0       0.0      0.0  0.0  
11  0.0    0.0       0.0      0.0  0.0  
12  0.0    0.0       0.0      0.0  0.0  
13  0.0    0.0       0.0      0.0  0.0  
14  0.0    0.0       0.0      0.0  0.0  
15  1.0    0.0       0.0      0.0  0.0  
16  0.0    1.0       0.0      0.0  0.0  
17  0.0    0.0       1.0      0.0  0.0  
18  0.0    0.0       0.0      1.0  0.0  
19  0.0    0.0       0.0      0.0  1.0  
20  0.0    0.0       0.0      0.0  0.0  
21  0.0    0.0       0.0      0.0  0.0  
22  0.0    0.0       0.0      0.0  0.0  
23  0.0    0.0       0.0      0.0  0.0  
24  0.0    0.0       0.0      0.0  0.0  
25  1.0    0.0       0.0      0.0  0.0  
26  0.0    1.0       0.0      0.0  0.0  
27  0.0    0.0       1.0      0.0  0.0  
28  0.0    0.0       0.0      1.0  0.0  
29  0.0    0.0       0.0      0.0  1.0

In [12]:
y_df

maas
0    2250
1    2500
2    3000
3    4000
4    5500
5    7500
6   10000
7   15000
8   25000
9   50000
10   2000
11   2500
12   4000
13   3000
14   5000
15   5000
16  12000
17  11000
18  15000
19  22000
20   2200
21   2200
22   2800
23   6000
24   5400
25   4000
26  12000
27  10000
28  15000
29  60000

In [13]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x_df,y_df,test_size=0.25,random_state=0)
x_test

Kidem  Puan  Cayci  Sekreter  Uzman Yardimcisi  Uzman  Proje Yoneticisi  \
2       5    70    0.0       0.0               1.0    0.0               0.0   
28      1    50    0.0       0.0               0.0    0.0               0.0   
13      4    38    0.0       0.0               0.0    1.0               0.0   
10      7    99    1.0       0.0               0.0    0.0               0.0   
26     10    81    0.0       0.0               0.0    0.0               0.0   
24      9    71    0.0       0.0               0.0    0.0               1.0   
27     10    38    0.0       0.0               0.0    0.0               0.0   
11      7     9    0.0       1.0               0.0    0.0               0.0   

    Sef  Mudur  Direktor  C-level  CEO  
2   0.0    0.0       0.0      0.0  0.0  
28  0.0    0.0       0.0      1.0  0.0  
13  0.0    0.0       0.0      0.0  0.0  
10  0.0    0.0       0.0      0.0  0.0  
26  0.0    1.0       0.0      0.0  0.0  
24  0.0    0.0       0.0      0.0  0.0  
27  0.0    0.0       1.0      0.0  0.0  
11  0.0    0.0       0.0      0.0  0.0

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [15]:
print(x_test.shape,x_train.shape)

(8, 12) (22, 12)


In [16]:
X_test = sc.fit_transform(x_test.iloc[:,0:2])
X_train = sc.fit_transform(x_train.iloc[:,0:2])

In [17]:
print(X_test.shape,X_train.shape)

(8, 2) (22, 2)


In [18]:
X_test = np.concatenate((X_test,x_test.iloc[:,2:]), axis=1)
X_train = np.concatenate((X_train,x_train.iloc[:,2:]), axis=1)

#### Multi Linear Regression

In [19]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [20]:
lr.fit(X_train,y_train)

lr_preds = lr.predict(X_test)
lr_preds

array([[ -218.63224646],
       [16693.72282602],
       [-5257.91886958],
       [ 7164.85817455],
       [12357.68096241],
       [10513.83059143],
       [15101.40476061],
       [ -300.98507081]])

In [21]:
from sklearn.metrics import r2_score

In [22]:
r2_score(lr_preds,y_test)

0.6313210957747415

#### Polynomial Regression

In [23]:
from sklearn.preprocessing import PolynomialFeatures

pol_reg2 = PolynomialFeatures(degree=4)
X_poly = pol_reg2.fit_transform(X_train)
lin_reg2 = LinearRegression()
lin_reg2.fit(X_poly,y_train)

LinearRegression()

In [24]:
polyreg_preds = lin_reg2.predict(pol_reg2.fit_transform(X_test))

r2_score(polyreg_preds, y_test)

0.6538671245758839

In [25]:
Y_train = sc.fit_transform(y_train)
Y_test = sc.fit_transform(y_test)

In [26]:
Y_train.ravel()

array([-0.09439152, -0.64457664, -0.32922663, -0.02729577,  0.84494894,
       -0.496966  , -0.42987025, -0.68483409, -0.66470537,  3.19330009,
       -0.16148726, -0.46341813,  0.17399147,  0.6436617 ,  2.52234262,
        0.17399147, -0.56406175, -0.56406175, -0.6814793 , -0.68483409,
       -0.496966  , -0.56406175])

#### Support Vector Machine Regression

In [27]:
from sklearn.svm import SVR
svr_reg = SVR(kernel = 'rbf')

svr_reg.fit(X_train, Y_train.ravel())
svr_preds = svr_reg.predict(X_test)

In [28]:
svr_preds

array([-0.32527556, -0.09975569, -0.30009783, -0.42175629, -0.08763864,
       -0.28814752, -0.20983437, -0.33273565])

In [29]:
r2_score(svr_preds, Y_test.ravel())

-71.5883014430289

#### Decision Tree

In [30]:
from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeRegressor(random_state=0)

In [31]:
dtr.fit(x_train, y_train)

r2_score(dtr.predict(x_test),y_test)

0.9602148768329865

#### Random Forest

In [32]:
from sklearn.ensemble import RandomForestRegressor
rf_reg=RandomForestRegressor(n_estimators = 10,random_state=0)
rf_reg.fit(x_train,y_train.values.ravel())

RandomForestRegressor(n_estimators=10, random_state=0)

In [33]:
r2_score(rf_reg.predict(x_test),y_test)

0.6890003836446679