In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
veriler = pd.read_csv("veriler.csv")

## Eksik Verilerin Doldurulması

In [3]:
veriler2 = pd.read_csv("eksikveriler.csv")

In [4]:
from sklearn.impute import SimpleImputer

In [5]:
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")

In [6]:
yas=veriler2.iloc[:,1:4].values

In [7]:
yas

array([[130.,  30.,  10.],
       [125.,  36.,  11.],
       [135.,  34.,  10.],
       [133.,  30.,   9.],
       [129.,  38.,  12.],
       [180.,  90.,  30.],
       [190.,  80.,  25.],
       [175.,  90.,  35.],
       [177.,  60.,  22.],
       [185., 105.,  33.],
       [165.,  55.,  27.],
       [155.,  50.,  44.],
       [160.,  58.,  nan],
       [162.,  59.,  41.],
       [167.,  62.,  55.],
       [174.,  70.,  47.],
       [193.,  90.,  nan],
       [187.,  80.,  27.],
       [183.,  88.,  28.],
       [159.,  40.,  29.],
       [164.,  66.,  32.],
       [166.,  56.,  42.]])

In [8]:
imputer=imputer.fit(yas)

In [9]:
yas = imputer.transform(yas)

In [10]:
yas

array([[130.  ,  30.  ,  10.  ],
       [125.  ,  36.  ,  11.  ],
       [135.  ,  34.  ,  10.  ],
       [133.  ,  30.  ,   9.  ],
       [129.  ,  38.  ,  12.  ],
       [180.  ,  90.  ,  30.  ],
       [190.  ,  80.  ,  25.  ],
       [175.  ,  90.  ,  35.  ],
       [177.  ,  60.  ,  22.  ],
       [185.  , 105.  ,  33.  ],
       [165.  ,  55.  ,  27.  ],
       [155.  ,  50.  ,  44.  ],
       [160.  ,  58.  ,  28.45],
       [162.  ,  59.  ,  41.  ],
       [167.  ,  62.  ,  55.  ],
       [174.  ,  70.  ,  47.  ],
       [193.  ,  90.  ,  28.45],
       [187.  ,  80.  ,  27.  ],
       [183.  ,  88.  ,  28.  ],
       [159.  ,  40.  ,  29.  ],
       [164.  ,  66.  ,  32.  ],
       [166.  ,  56.  ,  42.  ]])

## Kategorik Değerlerin Encoding Edilmesi

In [11]:
ulke = veriler.iloc[:,0:1].values

In [12]:
from sklearn import preprocessing

In [13]:
le = preprocessing.LabelEncoder()

In [14]:
ulke[:,0] = le.fit_transform(veriler.iloc[:,0])

In [15]:
print(ulke)

[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


In [16]:
ohe = preprocessing.OneHotEncoder()
ulke = ohe.fit_transform(ulke).toarray()

In [17]:
print(ulke)

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [18]:
sonuc = pd.DataFrame(data=ulke, index = range(22), columns= ["fr","tr","us"])

In [19]:
sonuc

fr   tr   us
0   0.0  1.0  0.0
1   0.0  1.0  0.0
2   0.0  1.0  0.0
3   0.0  1.0  0.0
4   0.0  1.0  0.0
5   0.0  1.0  0.0
6   0.0  1.0  0.0
7   0.0  1.0  0.0
8   0.0  1.0  0.0
9   0.0  0.0  1.0
10  0.0  0.0  1.0
11  0.0  0.0  1.0
12  0.0  0.0  1.0
13  0.0  0.0  1.0
14  0.0  0.0  1.0
15  1.0  0.0  0.0
16  1.0  0.0  0.0
17  1.0  0.0  0.0
18  1.0  0.0  0.0
19  1.0  0.0  0.0
20  1.0  0.0  0.0
21  1.0  0.0  0.0

In [20]:
sonuc2=pd.DataFrame(data=yas,index=range(22),columns=["boy","kilo","yas"])

In [21]:
sonuc3=pd.DataFrame(data=veriler.iloc[:,-1].values,index=range(22),columns=["cinsiyet"])

In [22]:
s=pd.concat([sonuc,sonuc2],axis=1)
s

fr   tr   us    boy   kilo    yas
0   0.0  1.0  0.0  130.0   30.0  10.00
1   0.0  1.0  0.0  125.0   36.0  11.00
2   0.0  1.0  0.0  135.0   34.0  10.00
3   0.0  1.0  0.0  133.0   30.0   9.00
4   0.0  1.0  0.0  129.0   38.0  12.00
5   0.0  1.0  0.0  180.0   90.0  30.00
6   0.0  1.0  0.0  190.0   80.0  25.00
7   0.0  1.0  0.0  175.0   90.0  35.00
8   0.0  1.0  0.0  177.0   60.0  22.00
9   0.0  0.0  1.0  185.0  105.0  33.00
10  0.0  0.0  1.0  165.0   55.0  27.00
11  0.0  0.0  1.0  155.0   50.0  44.00
12  0.0  0.0  1.0  160.0   58.0  28.45
13  0.0  0.0  1.0  162.0   59.0  41.00
14  0.0  0.0  1.0  167.0   62.0  55.00
15  1.0  0.0  0.0  174.0   70.0  47.00
16  1.0  0.0  0.0  193.0   90.0  28.45
17  1.0  0.0  0.0  187.0   80.0  27.00
18  1.0  0.0  0.0  183.0   88.0  28.00
19  1.0  0.0  0.0  159.0   40.0  29.00
20  1.0  0.0  0.0  164.0   66.0  32.00
21  1.0  0.0  0.0  166.0   56.0  42.00

In [23]:
s2=pd.concat([s,sonuc3],axis=1)
s2

fr   tr   us    boy   kilo    yas cinsiyet
0   0.0  1.0  0.0  130.0   30.0  10.00        e
1   0.0  1.0  0.0  125.0   36.0  11.00        e
2   0.0  1.0  0.0  135.0   34.0  10.00        k
3   0.0  1.0  0.0  133.0   30.0   9.00        k
4   0.0  1.0  0.0  129.0   38.0  12.00        e
5   0.0  1.0  0.0  180.0   90.0  30.00        e
6   0.0  1.0  0.0  190.0   80.0  25.00        e
7   0.0  1.0  0.0  175.0   90.0  35.00        e
8   0.0  1.0  0.0  177.0   60.0  22.00        k
9   0.0  0.0  1.0  185.0  105.0  33.00        e
10  0.0  0.0  1.0  165.0   55.0  27.00        k
11  0.0  0.0  1.0  155.0   50.0  44.00        k
12  0.0  0.0  1.0  160.0   58.0  28.45        k
13  0.0  0.0  1.0  162.0   59.0  41.00        k
14  0.0  0.0  1.0  167.0   62.0  55.00        k
15  1.0  0.0  0.0  174.0   70.0  47.00        e
16  1.0  0.0  0.0  193.0   90.0  28.45        e
17  1.0  0.0  0.0  187.0   80.0  27.00        e
18  1.0  0.0  0.0  183.0   88.0  28.00        e
19  1.0  0.0  0.0  159.0   40.0  29.00        k
20  1.0  0.0  0.0  164.0   66.0  32.00        k
21  1.0  0.0  0.0  166.0   56.0  42.00        k

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
x_train, x_test, y_train, y_test = train_test_split(s,sonuc3,test_size=0.33,random_state=0)

In [26]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [27]:
x_train = sc.fit_transform(x_train)

In [28]:
x_test=sc.fit_transform(x_test)